/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { RegionInfo, UnitDefinition, GeneralCategory, CurrencyInfo } from './types';

export const REGIONS: RegionInfo[] = [
  {
    id: 'dhaka',
    nameEn: 'Bangladesh – Standard (Dhaka)',
    nameBn: 'বাংলাদেশ – ঢাকা (স্ট্যান্ডার্ড)',
    allowedUnits: ['sqft', 'sqm', 'shotok', 'ojutangsho', 'chotak', 'katha', 'bigha', 'kani', 'acre', 'hectare'],
  },
  {
    id: 'chattogram',
    nameEn: 'Bangladesh – Chattogram',
    nameBn: 'বাংলাদেশ – চট্টগ্রাম',
    allowedUnits: ['sqft', 'sqm', 'shotok', 'ojutangsho', 'til', 'kranti', 'kora', 'gonda', 'kani', 'chotak', 'katha', 'bigha', 'acre', 'hectare'],
  },
  {
    id: 'sylhet',
    nameEn: 'Bangladesh – Sylhet',
    nameBn: 'বাংলাদেশ – সিলেট',
    allowedUnits: ['sqft', 'sqm', 'shotok', 'ojutangsho', 'poa', 'keyar', 'katha', 'bigha', 'acre', 'hectare'],
  },
  {
    id: 'khulna_barishal',
    nameEn: 'Bangladesh – Khulna & Barishal',
    nameBn: 'বাংলাদেশ – খুলনা ও বরিশাল',
    allowedUnits: ['sqft', 'sqm', 'shotok', 'ojutangsho', 'chotak', 'katha', 'bigha', 'kani', 'acre', 'hectare'],
  },
  {
    id: 'rajshahi_rangpur',
    nameEn: 'Bangladesh – Rajshahi & Rangpur',
    nameBn: 'বাংলাদেশ – রাজশাহী ও রংপুর (উত্তরবঙ্গ)',
    allowedUnits: ['sqft', 'sqm', 'shotok', 'ojutangsho', 'chotak', 'katha', 'bigha', 'kani', 'acre', 'hectare'],
  },
  {
    id: 'west_bengal',
    nameEn: 'India – West Bengal',
    nameBn: 'ভারত – পশ্চিমবঙ্গ',
    allowedUnits: ['sqft', 'sqm', 'shotok', 'ojutangsho', 'chotak', 'katha', 'bigha', 'acre', 'hectare'],
  },
  {
    id: 'assam',
    nameEn: 'India – Assam',
    nameBn: 'ভারত – আসাম',
    allowedUnits: ['sqft', 'sqm', 'shotok', 'lecha', 'katha', 'bigha', 'acre', 'hectare'],
  },
  {
    id: 'up_bihar',
    nameEn: 'India – North (UP/Bihar)',
    nameBn: 'ভারত – উত্তর প্রদেশ / বিহার',
    allowedUnits: ['sqft', 'sqm', 'biswa', 'bigha_pucca', 'acre', 'hectare'],
  },
  {
    id: 'punjab_sindh',
    nameEn: 'Pakistan – Punjab/Sindh',
    nameBn: 'পাকিস্তান – পাঞ্জাব / সিন্ধু',
    allowedUnits: ['sqft', 'sqm', 'marla', 'kanal', 'killa', 'murabba', 'acre', 'hectare'],
  },
];

export const LAND_UNITS: Record<string, UnitDefinition> = {
  sqft: { id: 'sqft', nameEn: 'Square Feet', nameBn: 'বর্গফুট', factor: 1, symbolEn: 'sq ft', symbolBn: 'বর্গফুট' },
  sqm: { id: 'sqm', nameEn: 'Square Meter', nameBn: 'বর্গমিটার', factor: 10.7639, symbolEn: 'sq m', symbolBn: 'বর্গমিটার' },
  acre: { id: 'acre', nameEn: 'Acre', nameBn: 'একর', factor: 43560, symbolEn: 'acre', symbolBn: 'একর' },
  hectare: { id: 'hectare', nameEn: 'Hectare', nameBn: 'হেক্টর', factor: 107639.104, symbolEn: 'ha', symbolBn: 'হেক্টর' },
  shotok: { id: 'shotok', nameEn: 'Shotok / Decimal', nameBn: 'শতক / ডেসিমেল', factor: 435.6, symbolEn: 'decimal', symbolBn: 'শতক' },
  ojutangsho: { id: 'ojutangsho', nameEn: 'Ojutangsho', nameBn: 'অযুতাংশ', factor: 4.356, symbolEn: 'ojutangsho', symbolBn: 'অযুতাংশ' },
  
  // Bengal / BD traditional units
  chotak: { id: 'chotak', nameEn: 'Chotak', nameBn: 'ছটাক', factor: 45, symbolEn: 'chotak', symbolBn: 'ছটাক' },
  katha: { id: 'katha', nameEn: 'Katha', nameBn: 'কাঠা', factor: 720, symbolEn: 'katha', symbolBn: 'কাঠা' },
  bigha: { id: 'bigha', nameEn: 'Bigha', nameBn: 'বিঘা', factor: 14400, symbolEn: 'bigha', symbolBn: 'বিঘা' },
  kani: { id: 'kani', nameEn: 'Kani', nameBn: 'কানি', factor: 17424, symbolEn: 'kani', symbolBn: 'কানি' },
  
  // Chattogram subdivision units
  gonda: { id: 'gonda', nameEn: 'Gonda', nameBn: 'গন্ডা', factor: 871.2, symbolEn: 'gonda', symbolBn: 'গন্ডা' },
  kora: { id: 'kora', nameEn: 'Kora', nameBn: 'কড়া', factor: 217.8, symbolEn: 'kora', symbolBn: 'কড়া' },
  kranti: { id: 'kranti', nameEn: 'Kranti', nameBn: 'ক্রান্তি', factor: 72.6, symbolEn: 'kranti', symbolBn: 'ক্রান্তি' },
  til: { id: 'til', nameEn: 'Til', nameBn: 'তিল', factor: 3.63, symbolEn: 'til', symbolBn: 'তিল' },
  
  // Sylhet subdivision units
  keyar: { id: 'keyar', nameEn: 'Keyar / Kedar', nameBn: 'কেয়ার / কেদার', factor: 13068, symbolEn: 'keyar', symbolBn: 'কেয়ার' },
  poa: { id: 'poa', nameEn: 'Poa', nameBn: 'পোয়া', factor: 3267, symbolEn: 'poa', symbolBn: 'পোয়া' },
  
  // Assam specific
  lecha: { id: 'lecha', nameEn: 'Lecha', nameBn: 'লেচা', factor: 144, symbolEn: 'lecha', symbolBn: 'লেচা' },
  
  // North India specific
  bigha_pucca: { id: 'bigha_pucca', nameEn: 'Bigha (Pucca)', nameBn: 'বিঘা (পাক্কা)', factor: 27225, symbolEn: 'bigha', symbolBn: 'বিঘা' },
  biswa: { id: 'biswa', nameEn: 'Biswa', nameBn: 'বিসোয়া', factor: 1361.25, symbolEn: 'biswa', symbolBn: 'বিসোয়া' },
  
  // Pakistan specific
  marla: { id: 'marla', nameEn: 'Marla', nameBn: 'মারলা', factor: 272.25, symbolEn: 'marla', symbolBn: 'মারলা' },
  kanal: { id: 'kanal', nameEn: 'Kanal', nameBn: 'কানাল', factor: 5445, symbolEn: 'kanal', symbolBn: 'কানাল' },
  killa: { id: 'killa', nameEn: 'Killa / Acre', nameBn: 'কিল্লা / একর', factor: 43560, symbolEn: 'killa', symbolBn: 'কিল্লা' },
  murabba: { id: 'murabba', nameEn: 'Murabba', nameBn: 'মুরাব্বা', factor: 1089000, symbolEn: 'murabba', symbolBn: 'মুরাব্বা' },
};

// General converter categories and units definitions
export const GENERAL_UNITS: Record<GeneralCategory, UnitDefinition[]> = {
  length: [
    { id: 'mm', nameEn: 'Millimeter', nameBn: 'মিলিমিটার', factor: 0.001, symbolEn: 'mm', symbolBn: 'মি.মি.' },
    { id: 'cm', nameEn: 'Centimeter', nameBn: 'সেন্টিমিটার', factor: 0.01, symbolEn: 'cm', symbolBn: 'সে.মি.' },
    { id: 'm', nameEn: 'Meter', nameBn: 'মিটার', factor: 1, symbolEn: 'm', symbolBn: 'মি.' },
    { id: 'km', nameEn: 'Kilometer', nameBn: 'কিলোমিটার', factor: 1000, symbolEn: 'km', symbolBn: 'কি.মি.' },
    { id: 'inch', nameEn: 'Inch', nameBn: 'ইঞ্চি', factor: 0.0254, symbolEn: 'in', symbolBn: 'ইঞ্চি' },
    { id: 'foot', nameEn: 'Foot', nameBn: 'ফুট', factor: 0.3048, symbolEn: 'ft', symbolBn: 'ফুট' },
    { id: 'yard', nameEn: 'Yard', nameBn: 'গজ (ইয়ার্ড)', factor: 0.9144, symbolEn: 'yd', symbolBn: 'গজ' },
    { id: 'mile', nameEn: 'Mile', nameBn: 'মাইল', factor: 1609.344, symbolEn: 'mi', symbolBn: 'মাইল' },
    // Traditional South Asian
    { id: 'haat', nameEn: 'Haat (18 inches)', nameBn: 'হাত (১৮ ইঞ্চি)', factor: 0.4572, symbolEn: 'haat', symbolBn: 'হাত' },
    { id: 'gaz', nameEn: 'Gaz (3 feet)', nameBn: 'গজ (৩ ফুট)', factor: 0.9144, symbolEn: 'gaz', symbolBn: 'গজ' },
  ],
  weight: [
    { id: 'mg', nameEn: 'Milligram', nameBn: 'মিলিগ্রাম', factor: 0.001, symbolEn: 'mg', symbolBn: 'মি.গ্রা.' },
    { id: 'g', nameEn: 'Gram', nameBn: 'গ্রাম', factor: 1, symbolEn: 'g', symbolBn: 'গ্রাম' },
    { id: 'kg', nameEn: 'Kilogram', nameBn: 'কিলোগ্রাম', factor: 1000, symbolEn: 'kg', symbolBn: 'কেজি' },
    { id: 'ton', nameEn: 'Metric Ton', nameBn: 'মেট্রিক টন', factor: 1000000, symbolEn: 't', symbolBn: 'টন' },
    { id: 'ounce', nameEn: 'Ounce', nameBn: 'আউন্স', factor: 28.349523, symbolEn: 'oz', symbolBn: 'আউন্স' },
    { id: 'pound', nameEn: 'Pound', nameBn: 'পাউন্ড', factor: 453.59237, symbolEn: 'lb', symbolBn: 'পাউন্ড' },
    // Traditional
    { id: 'tola', nameEn: 'Tola', nameBn: 'তোলা', factor: 11.664, symbolEn: 'tola', symbolBn: 'তোলা' },
    { id: 'chhatak_wt', nameEn: 'Chhatak (Weight)', nameBn: 'ছটাক (ওজন)', factor: 58.32, symbolEn: 'chhatak', symbolBn: 'ছটাক' },
    { id: 'poa_wt', nameEn: 'Poa (Weight)', nameBn: 'পোয়া (ওজন)', factor: 233.28, symbolEn: 'poa', symbolBn: 'পোয়া' },
    { id: 'seer', nameEn: 'Seer', nameBn: 'সের', factor: 933.12, symbolEn: 'seer', symbolBn: 'সের' },
    { id: 'maund', nameEn: 'Maund / Mon', nameBn: 'মণ', factor: 37324.8, symbolEn: 'maund', symbolBn: 'মণ' },
  ],
  temp: [
    { id: 'C', nameEn: 'Celsius', nameBn: 'সেলসিয়াস', factor: 1, symbolEn: '°C', symbolBn: '°C' },
    { id: 'F', nameEn: 'Fahrenheit', nameBn: 'ফারেনহাইট', factor: 1, symbolEn: '°F', symbolBn: '°F' },
    { id: 'K', nameEn: 'Kelvin', nameBn: 'কেলভিন', factor: 1, symbolEn: 'K', symbolBn: 'K' },
  ],
  area: [
    { id: 'sqmm', nameEn: 'Sq Millimeter', nameBn: 'বর্গ মিলিমিটার', factor: 0.000001, symbolEn: 'mm²', symbolBn: 'মি.মি.²' },
    { id: 'sqcm', nameEn: 'Sq Centimeter', nameBn: 'বর্গ সেন্টিমিটার', factor: 0.0001, symbolEn: 'cm²', symbolBn: 'সে.মি.²' },
    { id: 'sqm_gen', nameEn: 'Sq Meter', nameBn: 'বর্গমিটার', factor: 1, symbolEn: 'm²', symbolBn: 'মি.²' },
    { id: 'sqkm', nameEn: 'Sq Kilometer', nameBn: 'বর্গকিলোমিটার', factor: 1000000, symbolEn: 'km²', symbolBn: 'কি.মি.²' },
    { id: 'sqin', nameEn: 'Sq Inch', nameBn: 'বর্গইঞ্চি', factor: 0.00064516, symbolEn: 'in²', symbolBn: 'ইঞ্চি²' },
    { id: 'sqft_gen', nameEn: 'Sq Foot', nameBn: 'বর্গফুট', factor: 0.09290304, symbolEn: 'ft²', symbolBn: 'ফুট²' },
    { id: 'sqyd', nameEn: 'Sq Yard', nameBn: 'বর্গগজ', factor: 0.83612736, symbolEn: 'yd²', symbolBn: 'গজ²' },
    { id: 'sqmile', nameEn: 'Sq Mile', nameBn: 'বর্গমাইল', factor: 2589988.11, symbolEn: 'mi²', symbolBn: 'মাইল²' },
    { id: 'acre_gen', nameEn: 'Acre', nameBn: 'একর', factor: 4046.856422, symbolEn: 'acre', symbolBn: 'একর' },
    { id: 'hectare_gen', nameEn: 'Hectare', nameBn: 'হেক্টর', factor: 10000, symbolEn: 'ha', symbolBn: 'হেক্টর' },
  ],
  volume: [
    { id: 'ml', nameEn: 'Milliliter', nameBn: 'মিলিলিটার', factor: 1, symbolEn: 'ml', symbolBn: 'মি.লি.' },
    { id: 'l', nameEn: 'Liter', nameBn: 'লিটার', factor: 1000, symbolEn: 'L', symbolBn: 'লি.' },
    { id: 'gal_us', nameEn: 'Gallon (US)', nameBn: 'গ্যালন (ইউএস)', factor: 3785.411784, symbolEn: 'gal (US)', symbolBn: 'গ্যালন' },
    { id: 'gal_uk', nameEn: 'Gallon (UK)', nameBn: 'গ্যালন (ইউকে)', factor: 4546.09, symbolEn: 'gal (UK)', symbolBn: 'গ্যালন' },
    { id: 'cup', nameEn: 'Cup', nameBn: 'কাপ', factor: 236.588, symbolEn: 'cup', symbolBn: 'কাপ' },
    { id: 'tbsp', nameEn: 'Tablespoon', nameBn: 'টেবিল চামচ', factor: 14.7868, symbolEn: 'tbsp', symbolBn: 'চামচ (বড়)' },
    { id: 'tsp', nameEn: 'Teaspoon', nameBn: 'চা চামচ', factor: 4.92892, symbolEn: 'tsp', symbolBn: 'চামচ (ছোট)' },
  ],
  speed: [
    { id: 'mps', nameEn: 'Meter / Second', nameBn: 'মিটার / সেকেন্ড', factor: 1, symbolEn: 'm/s', symbolBn: 'মি./সে.' },
    { id: 'kmh', nameEn: 'Kilometer / Hour', nameBn: 'কিলোমিটার / ঘণ্টা', factor: 0.277778, symbolEn: 'km/h', symbolBn: 'কি.মি./ঘণ্টা' },
    { id: 'mph', nameEn: 'Miles / Hour', nameBn: 'মাইল / ঘণ্টা', factor: 0.44704, symbolEn: 'mph', symbolBn: 'মাইল/ঘণ্টা' },
    { id: 'knot', nameEn: 'Knot', nameBn: 'নট', factor: 0.514444, symbolEn: 'knot', symbolBn: 'নট' },
  ],
  time: [
    { id: 'sec', nameEn: 'Second', nameBn: 'সেকেন্ড', factor: 1, symbolEn: 's', symbolBn: 'সে.' },
    { id: 'min', nameEn: 'Minute', nameBn: 'মিনিট', factor: 60, symbolEn: 'min', symbolBn: 'মিনিট' },
    { id: 'hour', nameEn: 'Hour', nameBn: 'ঘণ্টা', factor: 3600, symbolEn: 'h', symbolBn: 'ঘণ্টা' },
    { id: 'day', nameEn: 'Day', nameBn: 'দিন', factor: 86400, symbolEn: 'd', symbolBn: 'দিন' },
    { id: 'week', nameEn: 'Week', nameBn: 'সপ্তাহ', factor: 604800, symbolEn: 'w', symbolBn: 'সপ্তাহ' },
    { id: 'month', nameEn: 'Month (30 Days)', nameBn: 'মাস (৩০ দিন)', factor: 2592000, symbolEn: 'mo', symbolBn: 'মাস' },
    { id: 'year', nameEn: 'Year (365 Days)', nameBn: 'বছর (৩৬৫ দিন)', factor: 31536000, symbolEn: 'yr', symbolBn: 'বছর' },
  ],
  data: [
    { id: 'B', nameEn: 'Byte', nameBn: 'বাইট', factor: 1, symbolEn: 'B', symbolBn: 'বাইট' },
    { id: 'KB', nameEn: 'Kilobyte (KB)', nameBn: 'কিলোবাইট (KB)', factor: 1024, symbolEn: 'KB', symbolBn: 'কেবি' },
    { id: 'MB', nameEn: 'Megabyte (MB)', nameBn: 'মেগাবাইট (MB)', factor: 1048576, symbolEn: 'MB', symbolBn: 'মেগা' },
    { id: 'GB', nameEn: 'Gigabyte (GB)', nameBn: 'গিগাবাইট (GB)', factor: 1073741824, symbolEn: 'GB', symbolBn: 'জিবি' },
    { id: 'TB', nameEn: 'Terabyte (TB)', nameBn: 'টেরাবাইট (TB)', factor: 1099511627776, symbolEn: 'TB', symbolBn: 'টিবি' },
  ],
};

// Featured Currencies list to place at the top
export const FEATURED_CURRENCIES: CurrencyInfo[] = [
  { code: 'BDT', nameEn: 'Bangladeshi Taka', nameBn: 'বাংলাদেশী টাকা', flag: '🇧🇩', symbol: '৳' },
  { code: 'AUD', nameEn: 'Australian Dollar', nameBn: 'অস্ট্রেলিয়ান ডলার', flag: '🇦🇺', symbol: 'A$' },
  { code: 'USD', nameEn: 'US Dollar', nameBn: 'ইউএস ডলার', flag: '🇺🇸', symbol: '$' },
  { code: 'GBP', nameEn: 'British Pound', nameBn: 'ব্রিটিশ পাউন্ড', flag: '🇬🇧', symbol: '£' },
  { code: 'EUR', nameEn: 'Euro', nameBn: 'ইউরো', flag: '🇪🇺', symbol: '€' },
  { code: 'SAR', nameEn: 'Saudi Riyal', nameBn: 'সৌদি রিয়াল', flag: '🇸🇦', symbol: 'SR' },
  { code: 'AED', nameEn: 'UAE Dirham', nameBn: 'সংযুক্ত আরব আমিরাত দিরহাম', flag: '🇦🇪', symbol: 'Dh' },
  { code: 'MYR', nameEn: 'Malaysian Ringgit', nameBn: 'মালয়েশিয়ান রিঙ্গিত', flag: '🇲🇾', symbol: 'RM' },
  { code: 'SGD', nameEn: 'Singapore Dollar', nameBn: 'সিঙ্গাপুর ডলার', flag: '🇸🇬', symbol: 'S$' },
  { code: 'INR', nameEn: 'Indian Rupee', nameBn: 'ভারতীয় রুপি', flag: '🇮🇳', symbol: '₹' },
];

export const OTHER_CURRENCIES: CurrencyInfo[] = [
  { code: 'CAD', nameEn: 'Canadian Dollar', nameBn: 'কানাডিয়ান ডলার', flag: '🇨🇦', symbol: 'C$' },
  { code: 'JPY', nameEn: 'Japanese Yen', nameBn: 'জাপানি ইয়েন', flag: '🇯🇵', symbol: '¥' },
  { code: 'CNY', nameEn: 'Chinese Yuan', nameBn: 'চীনা ইউয়ান', flag: '🇨🇳', symbol: '¥' },
  { code: 'KWD', nameEn: 'Kuwaiti Dinar', nameBn: 'কুয়েতি দিনার', flag: '🇰🇼', symbol: 'KD' },
  { code: 'OMR', nameEn: 'Omani Rial', nameBn: 'ওমানি রিয়াল', flag: '🇴🇲', symbol: 'RO' },
  { code: 'QAR', nameEn: 'Qatari Riyal', nameBn: 'কাতারি রিয়াল', flag: '🇶🇦', symbol: 'QR' },
  { code: 'NZD', nameEn: 'New Zealand Dollar', nameBn: 'নিউজিল্যান্ড ডলার', flag: '🇳🇿', symbol: 'NZ$' },
  { code: 'CHF', nameEn: 'Swiss Franc', nameBn: 'সুইস ফ্রাঁ', flag: '🇨🇭', symbol: 'CHF' },
  { code: 'ZAR', nameEn: 'South African Rand', nameBn: 'দক্ষিণ আফ্রিকান র‍্যান্ড', flag: '🇿🇦', symbol: 'R' },
  { code: 'KWD_D', nameEn: 'Kuwaiti Dinar', nameBn: 'কুয়েতি দিনার', flag: '🇰🇼', symbol: 'KD' },
  { code: 'BHD', nameEn: 'Bahraini Dinar', nameBn: 'বাহরাইনি দিনার', flag: '🇧🇭', symbol: 'BD' },
  { code: 'KRW', nameEn: 'South Korean Won', nameBn: 'দক্ষিণ কোরিয়ান উন', flag: '🇰🇷', symbol: '₩' },
  { code: 'TRY', nameEn: 'Turkish Lira', nameBn: 'তুর্কি লিরা', flag: '🇹🇷', symbol: '₺' },
  { code: 'PKR', nameEn: 'Pakistani Rupee', nameBn: 'পাকিস্তানি রুপি', flag: '🇵🇰', symbol: '₨' },
  { code: 'NPR', nameEn: 'Nepalese Rupee', nameBn: 'নেপালি রুপি', flag: '🇳🇵', symbol: '₨' },
  { code: 'LKR', nameEn: 'Sri Lankan Rupee', nameBn: 'শ্রীলঙ্কান রুপি', flag: '🇱🇰', symbol: '₨' },
  { code: 'MVR', nameEn: 'Maldivian Rufiyaa', nameBn: 'মালদ্বীপের রুফিয়া', flag: '🇲🇻', symbol: 'Rf' },
  { code: 'RUB', nameEn: 'Russian Ruble', nameBn: 'রাশিয়ান রুবল', flag: '🇷🇺', symbol: '₽' },
  { code: 'BRL', nameEn: 'Brazilian Real', nameBn: 'ব্রাজিলিয়ান রিয়াল', flag: '🇧🇷', symbol: 'R$' },
  { code: 'MXN', nameEn: 'Mexican Peso', nameBn: 'মেক্সিকান পেসো', flag: '🇲🇽', symbol: '$' },
  { code: 'IDR', nameEn: 'Indonesian Rupiah', nameBn: 'ইন্দোনেশিয়ান রুপিয়াহ', flag: '🇮🇩', symbol: 'Rp' },
  { code: 'THB', nameEn: 'Thai Baht', nameBn: 'থাই বাট', flag: '🇹🇭', symbol: '฿' },
  { code: 'VND', nameEn: 'Vietnamese Dong', nameBn: 'ভিয়েতনামী ডং', flag: '🇻🇳', symbol: '₫' },
  { code: 'PHP', nameEn: 'Philippine Peso', nameBn: 'ফিলিপাইন পেসো', flag: '🇵🇭', symbol: '₱' },
  { code: 'KZT', nameEn: 'Kazakhstani Tenge', nameBn: 'কাজাখস্তানি টেঙ্গে', flag: '🇰🇿', symbol: '₸' },
];

export const FALLBACK_CURRENCY_RATES: Record<string, number> = {
  USD: 1.0,
  BDT: 118.5,
  AUD: 1.52,
  GBP: 0.79,
  EUR: 0.93,
  SAR: 3.75,
  AED: 3.67,
  MYR: 4.71,
  SGD: 1.35,
  INR: 83.50,
  CAD: 1.37,
  JPY: 161.2,
  CNY: 7.27,
  KWD: 0.31,
  OMR: 0.38,
  QAR: 3.64,
  NZD: 1.65,
  CHF: 0.90,
  ZAR: 18.2,
  BHD: 0.38,
  KRW: 1380.0,
  TRY: 32.8,
  PKR: 278.5,
  NPR: 133.6,
  LKR: 305.0,
  MVR: 15.4,
  RUB: 87.5,
  BRL: 5.5,
  MXN: 18.3,
  IDR: 16350.0,
  THB: 36.7,
  VND: 25450.0,
  PHP: 58.7,
  KZT: 472.0,
};

export const TRANSLATIONS = {
  en: {
    appName: 'ShohojHishab',
    appSubtitle: 'Unit & Land Converter',
    landConverter: 'Land Converter',
    generalConverter: 'General Converter',
    currency: 'Currency',
    selectRegion: 'Select your region / Bangladesh or South Asia',
    selectRegionLabel: 'Your Region',
    fromUnit: 'From',
    toUnit: 'To',
    enterValue: 'Enter value',
    convertToAll: 'Convert to ALL units',
    compoundFormat: 'Traditional Compound Breakdown',
    offlineBanner: 'Offline — showing cached rates from',
    ratesUpdated: 'Rates updated:',
    midMarketDisclaimer: 'Mid-market rates shown. Remittance operators charge different fees and rates.',
    compareTaptap: 'Compare on Taptap Send ↗',
    disclaimer: 'Values follow common regional standards and may differ locally. Always verify with official land records (e.g., BD Land Ministry / AC Land office) before any transaction.',
    about: 'About',
    aboutTitle: 'About ShohojHishab',
    aboutDescription: 'ShohojHishab (সহজহিসাব) is a warm, cozy utility designed to simplify complex unit conversions for land and daily metrics. Created with care to bring simplicity to regional land systems, domestic calculations, and live financial remittance corridors.',
    close: 'Close',
    digitsToggle: 'Show Bengali Numbers',
    copySuccess: 'Copied to clipboard!',
    details: 'Details / Formulas',
    categories: {
      length: 'Length 📏',
      area: 'Area 🗺️',
      weight: 'Weight ⚖️',
      temp: 'Temperature 🌡️',
      volume: 'Volume 🧪',
      speed: 'Speed ⚡',
      time: 'Time ⏰',
      data: 'Data 💾',
    },
    compareBtn: 'Compare',
    quickCorridors: 'Quick Remittance Pairs',
    bengaliDigits: 'Bengali Digits (০-৯)',
    englishDigits: 'English Digits (0-9)',
    formulaInfo: 'Formula Information',
    noNegative: 'Negative values are not allowed for this conversion.',
    developerCredit: 'Developed by Ashraful Islam',
  },
  bn: {
    appName: 'সহজহিসাব',
    appSubtitle: 'ইউনিট ও জমি কনভার্টার',
    landConverter: 'জমি কনভার্টার',
    generalConverter: 'সাধারণ কনভার্টার',
    currency: 'কারেন্সি',
    selectRegion: 'আপনার অঞ্চল নির্বাচন করুন',
    selectRegionLabel: 'আপনার অঞ্চল',
    fromUnit: 'থেকে',
    toUnit: 'ইনপুট',
    enterValue: 'মান লিখুন',
    convertToAll: 'সব ইউনিটে রূপান্তর',
    compoundFormat: 'ঐতিহ্যগত যৌগিক রূপান্তর',
    offlineBanner: 'অফলাইন — সংরক্ষিত রেটের তারিখ:',
    ratesUpdated: 'আপডেটের তারিখ:',
    midMarketDisclaimer: 'এখানে মিড-মার্কেট রেট দেখানো হয়েছে। রেমিট্যান্স অ্যাপের রেট ও ফি আলাদা হতে পারে।',
    compareTaptap: 'Taptap Send-এ তুলনা করুন ↗',
    disclaimer: 'মানগুলো প্রচলিত আঞ্চলিক মান অনুসারে; স্থানভেদে ভিন্ন হতে পারে। জমি কেনাবেচার আগে সরকারি রেকর্ড যাচাই করুন। (যেমন: ভূমি মন্ত্রণালয় / এসিল্যান্ড অফিস)',
    about: 'সম্পর্কে',
    aboutTitle: 'সহজহিসাব সম্পর্কে',
    aboutDescription: 'সহজহিসাব হচ্ছে একটি ঘরোয়া ও সহজ মাপজোখ অ্যাপ, যা জমি এবং দৈনন্দিন হিসাব-নিকাশকে সহজ করার জন্য তৈরি করা হয়েছে। এটি আমাদের দেশের বিভিন্ন আঞ্চলিক হিসাব, পারিবারিক টুকিটাকি পরিমাপ এবং রেমিট্যান্স সংক্রান্ত সঠিক তথ্য দিতে অত্যন্ত সাহায্য করবে।',
    close: 'বন্ধ করুন',
    digitsToggle: 'বাংলা সংখ্যায় দেখুন',
    copySuccess: 'কপি করা হয়েছে!',
    details: 'বিস্তারিত / সূত্র',
    categories: {
      length: 'দৈর্ঘ্য 📏',
      area: 'ক্ষেত্রফল 🗺️',
      weight: 'ওজন ⚖️',
      temp: 'তাপমাত্রা 🌡️',
      volume: 'আয়তন 🧪',
      speed: 'গতিবেগ ⚡',
      time: 'সময় ⏰',
      data: 'ডেটা 💾',
    },
    compareBtn: 'তুলনা করুন',
    quickCorridors: 'সহজ রেমিট্যান্স পেয়ার',
    bengaliDigits: 'বাংলা সংখ্যা (০-৯)',
    englishDigits: 'ইংরেজি সংখ্যা (0-9)',
    formulaInfo: 'হিসাবের নিয়মাবলী',
    noNegative: 'এই হিসাবের জন্য ঋণাত্মক মান গ্রহণযোগ্য নয়।',
    developerCredit: 'ডেভেলপার: আশরাফুল ইসলাম',
  },
};
